# Generated by Django 3.1.3 on 2020-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_show_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
