# Generated by Django 3.1.3 on 2020-11-10 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20201110_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='airdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
