# Generated by Django 3.1.3 on 2020-11-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_stshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stshow',
            old_name='show_id',
            new_name='show',
        ),
    ]
