# Generated by Django 3.1.3 on 2020-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0005_show_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show',
            new_name='show_num',
        ),
        migrations.AddField(
            model_name='show',
            name='poster_path',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
