# Generated by Django 3.1.3 on 2020-11-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201117_0747'),
        ('tv', '0006_auto_20201116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='stshow',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
