# Generated by Django 3.1.3 on 2020-11-21 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0007_stshow_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='airdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
