# Generated by Django 3.1.3 on 2020-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0008_auto_20201121_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='airdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
