# Generated by Django 3.1.3 on 2020-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0009_auto_20201121_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='airdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
